### ISSUE TITLE
Manual control of outputs resets all output pins

### ISSUE THREAD

**Issue by philipstarkey** [labscript-suite/PrawnBlaster#24]
Currently sending a `go high` or `go low` command calls `configure_gpio()` which resets every output pin. This means all pins are set low, and then the `go high/low` command is executed. This is a bug!

Not entirely sure how to fix it right now as there are a lot of different pathways that utilise the GPIO pins and I need to consider them all. Possibly I should be calling `configure_gpio()` after shots and after a pin change? (so a pin change for any pseudoclock would reset all outputs to 0). That probably causes issues though because it fills in missing pins....which I want to defer until after all pin sets have been complete. Might also need to ensure it's called once before the first shot is ever run if it hasn't been called some other way. Anyway....some complexities to resolve. A low priority bug because most people probably don't need this functionality.

**Comment by BryanFRezende** [comment]
When controlling pseudoclock outputs through BLACS, only the last clock responds to the command. I was about to post a separate issue, but I think what I've encountered is a manifestation of the problem described above.

E.g. if all clocks are initialized, [0,1,2,3], only pseudoclock (PS)3 will respond to being turned on in the BLACS instrument panel. Trying to toggle PS0, PS1, or PS2 results in a millisecond (ms) order time scale blip before going low. Further, if PS2 is toggled on while toggling on any other PS, PS3 will momentarily go low while the blips occur on the other PS' before going back high. See scope trace (PS[0,1,2,3] <--> [yellow, green, blue, magenta] scope trace).

![PrawnBlaster_PS_Bug-scope_trace](https://github.com/labscript-suite/PrawnBlaster/assets/73176459/659f1702-cb30-431c-ae3e-dad0e19ae7a7)

This makes sense now, given that issuing the `go high/low` command resets all the pins. I'm also not sure how many people need the functionality, but it's pretty unexpected behavior for anyone testing the outputs from the BLACS panel :raised_hand::neutral_face:.

It doesn't seem as relevant but in case it is and since I already did it, here is the reproduction of the issue depicted in the scope trace in a python script.

```python
# Suspect block of code found in ~\labscript-suite\labscript-devices\labscript_devices\PrawnBlaster\blacs_workers.py
# line 196 --> program_manual()
# The bug behavior was reproduced with code below. In this test, the PrawnBlaster has already received a prior
# command to initialize all four pseudoclocks.

import serial
import time

# suspect function reproduction
def program_manual_bugTest(values):
    for channel, value in values.items():
        
        if value:
            conn.write(b"go high %d\r\n" % channel)
        else:
            conn.write(b"go low %d\r\n" % channel)
        
        assert conn.readline().decode() == 'ok\r\n', f'Response was: {resp}'
    return values

# specify output values as if turning on all pseudoclock control buttons in BLACS
outputValues = {0: True, 1: True, 2: True, 3: True}

# connection parameters
PICO_PORT = 'COM7'
BAUD = 115200
TIMEOUT = 0.1

# establish connection
conn = serial.Serial(PICO_PORT, baudrate = BAUD, timeout = TIMEOUT)

# run function
program_manual_bugTest(outputValues)

# close connection
conn.close()
```

**Comment by dihm** [comment]
Thinking about this a bit, I think a fairly easy method to minimize the issue is to put the `gpio_init` code behind a mutex that stores which core has last run it. Then we can at least keep runs of this function to the bare minimum required.

That said, `gpio_put` is supposed to be atomic and should support multi-core operation so I'm not entirely sure why we need to re-call `gpio_init` when switching between manual and buffered control. I assume it has something to do with the PIO taking control, but I can't find how that works or why in the docs or online. It would just be nicer if there was a way to switch between manual and buffered mode that didn't require resetting the outputs to default input state.

**Comment by philipstarkey** [comment]
> It would just be nicer if there was a way to switch between manual and buffered mode that didn't require resetting the outputs to default input state.

I believe this could be done if a short program was written for the other PIO core? My memory from reading the documentation is that all state machines can be configured to access the same pins, and there is some conflict resolution that goes on if multiple state machines try to change the output on the same tick. It's possible this doesn't work across PIO cores, but I have a feeling it does.

That way we could always have the pins configured for PIO use and we'd just need to write commands to a special PIO program that toggled the relevant pin (e.g. `OUT PINS` or whatever it is).

Oh, we'd probably need 4 state machines due to the fact that output pins might not be adjacent to each other. But we have that many spare on the second core so it should be fine 🤷

**Comment by dihm** [comment]
You know, the more I think about this, the more I don't think we need to ensure pins don't reset when toggling between manual and buffered mode (for the prawnblaster specifically). Since all the outputs are pseudoclocks anyway, they must be set low at the start of buffered execution regardless. As such, I can't see much reason why we would want to prevent blanking in all situations. I think mutex protecting `gpio_init` should be a fairly easy upgrade that solves the immediate issue with the least effort.

Now the plain digital outputs of the Prawn_DO is a different animal which would strongly benefit from the outputs not blanking during any programming. Doing the bigger lift of manual updates via PIO there would likely be worth it.
